# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.4.1"

package:
  name: ansible-runner
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ansible-runner/ansible_runner-${{ version }}.tar.gz
  sha256: 11d717da4dd8d93d56703a4a98e5f2154026a7ed1b46d9930902b8298dc67d09

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps --disable-pip-version-check
  python:
    entry_points:
      - ansible-runner = ansible_runner.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=45,<=69.0.2
    - setuptools_scm >=6.2,<=8.0
  run:
    - importlib-metadata >=4.6
    - packaging
    - pexpect >=4.5
    - python >=${{ python_min }}
    - python-daemon
    - pyyaml

tests:
  - python:
      imports: ansible_runner
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - test/
      recipe:
        - run_test.py
    requirements:
      run:
        - ansible
        - ansible-core
        - coverage
        - pytest
        - pytest-mock
        - pytest-timeout
        - python ${{ python_min }}.*
        - if: win
          then:
            - m2-grep
    script:
      - ansible-runner --version
      - ansible-runner --help
      - ansible-runner --version | grep -iE "${{ version | replace('.', '\\.') }}"
      - python run_test.py

about:
  license: Apache-2.0
  license_file: LICENSE.md
  summary: |
    A tool and python library that helps when interfacing with Ansible directly
    or as part of another system whether that be through a container image
    interface, as a standalone tool, or as a Python module that can be
    imported. The goal is to provide a stable and consistent interface
    abstraction to Ansible.


  homepage: https://github.com/ansible/ansible-runner
  documentation: https://ansible-runner.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
